### ISSUE TITLE
您好，我在运行该项目时提示 需要一个setting.json 文件，但是该文件是gitignore的

### ISSUE THREAD

**Issue by lingluan533** [520MianXiangDuiXiang520/SimpleCA#2]
panic: setting Uninitialized！

goroutine 1 [running]:
simple_ca/src.GetSetting(...)
	/root/Downloads/SimpleCA-main/src/setting.go:111
main.init.0()
	/root/Downloads/SimpleCA-main/main.go:12 +0xf6
请问是否能够提供一下该文件或者文件模板呢，谢谢。

**Comment by 520MianXiangDuiXiang520** [comment]
已经上传

**Comment by lingluan533** [comment]
多谢
