### ISSUE TITLE
ca简单认证我也是 不会调试出来这两个结果

### ISSUE THREAD

**Issue by grhandm** [520MianXiangDuiXiang520/SimpleCA#3]
求楼主指导一下 谢谢
panic: setting Uninitialized！

goroutine 1 [running]:
simple_ca/src.GetSetting(...)
        C:/Users/MECHREVO/gows/gopath/src/SimpleCA-main/src/setting.go:111
main.init.0()
        C:/Users/MECHREVO/gows/gopath/src/SimpleCA-main/main.go:12 +0xa5

进程 已完成，退出代码为 2
panic: can not open root private

goroutine 1 [running]:
simple_ca/src/tools.init.0()
	C:/Users/MECHREVO/gows/gopath/src/SimpleCA-main/src/tools/certificate_test.go:44 +0xc5
FAIL	simple_ca/src/tools	0.041s

**Comment by 520MianXiangDuiXiang520** [comment]
重命名 [setting_example.json](https://github.com/520MianXiangDuiXiang520/SimpleCA/blob/main/setting_example.json) 为 setting.json 并运行

**Comment by grhandm** [comment]
楼主有 联系方式吗 我想加你 这上面不太方便

**Comment by grhandm** [comment]
现在编译没有问题了 运行我看要说访问哪个网页 不知道怎么操作了 求助楼主

**Comment by 520MianXiangDuiXiang520** [comment]
https://github.com/520MianXiangDuiXiang520/SimpleCAWeb

**Comment by grhandm** [comment]
楼主给个联系方式吧 想问问你细节 不会让你白解答的

**Comment by grhandm** [comment]
1608104692 这是我wx和qq

**Comment by 520MianXiangDuiXiang520** [comment]
有啥问题直接发邮件吧

**Comment by grhandm** [comment]
大佬 我试了各种方法 一直报错 卡在了npm run server 
Node.js v19.6.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-ca@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-ca@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MECHREVO\AppData\Roaming\npm-cache\_logs\2023-02-21T05_53_56_442Z-debug.log

**Comment by grhandm** [comment]
楼主 这个前端的node是哪个版本呀 node-sass

**Comment by grhandm** [comment]
现在出现这些信息 我知道他这个版本不太匹配 但4.0.0是不是有点太老了
ERROR  Failed to compile with 1 errors                                                                         15:08:08

 error  in ./src/element-variables.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass version 8.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (C:\Users\MECHREVO\Downloads\Compressed\SimpleCAWeb-main\node_modules\sass-loader\dist\index.js:165:13)
    at Object.loader (C:\Users\MECHREVO\Downloads\Compressed\SimpleCAWeb-main\node_modules\sass-loader\dist\index.js:79:18)

**Comment by grhandm** [comment]
牛逼 楼主 我解决完了

**Comment by grhandm** [comment]
哈哈哈哈 问了你 环境变量基础的问题
