### ISSUE TITLE
您还没有登录呢

### ISSUE THREAD

**Issue by grhandm** [520MianXiangDuiXiang520/SimpleCA#4]
现在node 和 goland 都配置好了 先启动goland 再启动node 然后输入那个网址 进去之后 我点 我的证书 他说我还没有登录 
楼主 这个登录的入口在哪呀

**Comment by 520MianXiangDuiXiang520** [comment]
你可以直接访问 127.0.0.1/登陆.html 尝试一下，这个功能并不是我实现的，如果还有问题可以在 SimpleCAWeb 下面提 issuse
