### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by grhandm** [520MianXiangDuiXiang520/SimpleCA#5]
web作者说 让我过来问一下您 说您整合的 他记得不太清楚了，现在主要就是登录不了 我启动服务 都能运行 就是点的时候说我还没有登录  您给我那个网页 启动服务之后 访问说拒绝 您方便给我远程一下吗

**Comment by 520MianXiangDuiXiang520** [comment]
双击 login/login.html 打开

**Comment by grhandm** [comment]
login里面的文件是登录html 然后我点击之后注册 登录 说请求失败 然后我直接访问 您跟我说那个网址 127.0.0.1/登陆.html 说拒绝访问
